version: "3.8"

services:
  mariadb:
    image: mariadb:11.3
    container_name: papchat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: papchatdb
      MYSQL_USER: papchatuser
      MYSQL_PASSWORD: papchatpass
    ports:
      - "3306:3306"
    networks:
      - dbnet
    command:
      - --default-authentication-plugin=mysql_native_password

volumes:
  mariadb_data:

networks:
  dbnet:
